local-up:
	docker-compose -f docker-compose.local.yml up -d

local-down:
	docker-compose -f docker-compose.local.yml down

local-restart:
	docker-compose -f docker-compose.local.yml restart

local-logs:
	docker-compose -f docker-compose.local.yml logs -f

local-shell:
	docker-compose -f docker-compose.local.yml exec -it backend sh