# Generated by Django 5.2.7 on 2025-11-07 12:23

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoOwner',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('https_url', models.URLField(unique=True)),
                ('ssh_url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('size_in_kb', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=100)),
                ('latest_commit_sha', models.CharField(max_length=40)),
                ('previous_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repoowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretScanResult',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_line', models.IntegerField(blank=True, null=True)),
                ('committer_email', models.TextField(blank=True, null=True)),
                ('commit_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('secret_type', models.CharField(max_length=100)),
                ('secret_value', models.TextField()),
                ('secret_value_rawv2', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_rotated', models.BooleanField(default=False)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('repo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
