# Generated by Django 5.2.7 on 2025-10-20 10:32

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoOwner',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('https_url', models.URLField(unique=True)),
                ('ssh_url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('size_in_kb', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=100)),
                ('latest_commit_sha', models.CharField(max_length=40)),
                ('previous_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repoowner')),
            ],
        ),
    ]
