# Generated by Django 5.2.8 on 2025-11-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repoowner_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretscanresult',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
    ]
